
name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe what you expected to happen...
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true
  
  - type: dropdown
    id: app
    attributes:
      label: Application
      description: Which application is affected?
      options:
        - Marketing Website
        - Chrome Extension
        - Mobile App
        - Other (specify in description)
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: "e.g., 2.0.0"
    validations:
      required: false
  
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false
  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., macOS 14.0, Windows 11, Ubuntu 22.04"
    validations:
      required: false
  
  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell
    validations:
      required: false
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
